### ISSUE TITLE
Cannot import citrine in python 3.5

### ISSUE THREAD

**Issue by maxhutch** [CitrineInformatics/citrine-python#204]
In a fresh python 3.5 conda environment, I get:
```python
In [1]: import citrine                                                                                  
Traceback (most recent call last):

  File "/home/maxhutch/anaconda3/envs/py3.5/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-2b383dd42cdf>", line 1, in <module>
    import citrine

  File "/home/maxhutch/anaconda3/envs/py3.5/lib/python3.5/site-packages/citrine/__init__.py", line 2, in <module>
    from citrine.citrine import Citrine  # noqa: F401

  File "/home/maxhutch/anaconda3/envs/py3.5/lib/python3.5/site-packages/citrine/citrine.py", line 7
    DEFAULT_HOST: str = 'citrine.io'
                ^
SyntaxError: invalid syntax
```

Reproduction steps:
```bash
$ conda create -n py3.5 python=3.5
$ conda activate py3.5
$ pip install citrine
$ pip install ipython
$ ipython
In [1]: import citrine     
```

**Comment by gregor-robinson** [comment]
I can reproduce this.

**Comment by maxhutch** [comment]
@bfolie and I think this is because the strip-hints script isn't be applied to the wheel/tarball that's being deployed to pypi.

**Comment by kroenlein** [comment]
I cannot replicate this issue.  @gregor-robinson @maxhutch Can we verify this issue again, or I will close it as being fixed elsewhere.

**Comment by maxhutch** [comment]
I think this was closed in https://github.com/CitrineInformatics/citrine-python/pull/239
